### ISSUE TITLE
`try_verify_against_date_command_format` fail when `LANG` is set to other locale

### ISSUE THREAD

**Issue by scarf005** [chronotope/chrono#1060]
## Summary

GNU `date` uses environment variable `LANG` to localize its input, however `try_verify_against_date_command_format` does not explicitly set `LANG`, which makes the test fail when `date` is set to another locale.

## Reproduction

(asked in https://github.com/chronotope/chrono/issues/1060#issuecomment-1565855641)

<details><summary>with `LANG=ko_KR.UTF-8`</summary>

```
 ~/r/chrono   locale …  bash                                                                                                                                                                                     2023년 05월 28일 (일) 오후 01시 05분 44초scarf@TG02:~/repo/chrono$ export LANG=ko_KR.UTF-8
scarf@TG02:~/repo/chrono$ date
2023. 05. 28. (일) 13:05:49 KST
scarf@TG02:~/repo/chrono$ cargo test --package chrono --test dateutils --features unstable-locales -- try_verify_against_date_command_format --exact --nocapture 
   Compiling chrono v0.4.24 (/home/scarf/repo/chrono)
    Finished test [unoptimized + debuginfo] target(s) in 1.01s
     Running tests/dateutils.rs (target/debug/deps/dateutils-917f84c226dfcdb1)

running 1 test
thread 'try_verify_against_date_command_format' panicked at 'assertion failed: `(left == right)`
  left: `"d01 D01/01/70 F1970-01-01 H12 I12 j001 k12 l12 m01 M11 S13 T12:11:13 u4 U00 w4 W00 X12시 11분 13초 y70 Y1970 z+09:00\n"`,
 right: `"d01 D01/01/70 F1970-01-01 H12 I12 j001 k12 l12 m01 M11 S13 T12:11:13 u4 U00 w4 W00 X12:11:13 y70 Y1970 z+09:00\n"`', tests/dateutils.rs:121:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test try_verify_against_date_command_format ... FAILED

failures:

failures:
    try_verify_against_date_command_format

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s

error: test failed, to rerun pass `-p chrono --test dateutils`
scarf@TG02:~/repo/chrono$ 
```

</details> 

<details><summary>with `LANG=c`</summary>

scarf@TG02:~/repo/chrono$ export LANG=c
scarf@TG02:~/repo/chrono$ date
Sun May 28 13:06:42 KST 2023
scarf@TG02:~/repo/chrono$ cargo test --package chrono --test dateutils --features unstable-locales -- try_verify_against_date_command_format --exact --nocapture 
    Finished test [unoptimized + debuginfo] target(s) in 0.03s
     Running tests/dateutils.rs (target/debug/deps/dateutils-917f84c226dfcdb1)

running 1 test
test try_verify_against_date_command_format ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.14s

scarf@TG02:~/repo/chrono$ 

</details> 

## Details

```sh
> echo $LANG
ko_KR.UTF-8
```

<details><summary>Error log</summary>

```sh
 *  Executing task: cargo test --package chrono --test dateutils --features unstable-locales -- try_verify_against_date_command_format --exact --nocapture 

    Finished test [unoptimized + debuginfo] target(s) in 0.03s
     Running tests/dateutils.rs (target/debug/deps/dateutils-917f84c226dfcdb1)

running 1 test
thread 'try_verify_against_date_command_format' panicked at 'assertion failed: `(left == right)`
  left: `"d01 D01/01/70 F1970-01-01 H12 I12 j001 k12 l12 m01 M11 S13 T12:11:13 u4 U00 w4 W00 X12시 11분 13초 y70 Y1970 z+09:00\n"`,
 right: `"d01 D01/01/70 F1970-01-01 H12 I12 j001 k12 l12 m01 M11 S13 T12:11:13 u4 U00 w4 W00 X12:11:13 y70 Y1970 z+09:00\n"`', tests/dateutils.rs:121:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:211:5
   4: dateutils::verify_against_date_command_format_local
             at ./tests/dateutils.rs:121:5
   5: dateutils::try_verify_against_date_command_format
             at ./tests/dateutils.rs:135:9
   6: dateutils::try_verify_against_date_command_format::{{closure}}
             at ./tests/dateutils.rs:126:45
   7: core::ops::function::FnOnce::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:250:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test try_verify_against_date_command_format ... FAILED

failures:

failures:
    try_verify_against_date_command_format

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.01s

error: test failed, to rerun pass `-p chrono --test dateutils`

 *  The terminal process "cargo 'test', '--package', 'chrono', '--test', 'dateutils', '--features', 'unstable-locales', '--', 'try_verify_against_date_command_format', '--exact', '--nocapture'" failed to launch (exit code: 101). 
 *  Terminal will be reused by tasks, press any key to close it. 
```

</details>

**Comment by scarf005** [comment]
i found it when testing #1058 locally.

**Comment by jtmoon79** [comment]
@scarf005 can you post or link to the testing source code?

**Comment by scarf005** [comment]
@jtmoon79 could you clarify? if you meant which test is failing: https://github.com/chronotope/chrono/blob/9dfa7b0028123ec3c728487443e8431adb4dc1e7/tests/dateutils.rs#L124-L139

**Comment by jtmoon79** [comment]
> @jtmoon79 could you clarify? if you meant which test is failing: https://github.com/chronotope/chrono/blob/9dfa7b0028123ec3c728487443e8431adb4dc1e7/tests/dateutils.rs#L124-L139

Ah okay, I misunderstood that this was your own extra test you added. Thanks for the link.

**Comment by jtmoon79** [comment]
@scarf005 what happens if you run these three commands. (I'm pretty sure the same crash. I want to verify my understanding of when `LANG` is set and is not set).

```text
# export LANG=ko_KR.UTF-8
# date
# cargo test --package chrono --test dateutils --features unstable-locales -- try_verify_against_date_command_format --exact --nocapture 
```

Would you please copy+paste the console output?

**Comment by scarf005** [comment]
@jtmoon79 sure. I've updated issue body to be more descriptive.


<details><summary>with `LANG=ko_KR.UTF-8`</summary>

```
 ~/r/chrono   locale …  bash                                                                                                                                                                                     2023년 05월 28일 (일) 오후 01시 05분 44초scarf@TG02:~/repo/chrono$ export LANG=ko_KR.UTF-8
scarf@TG02:~/repo/chrono$ date
2023. 05. 28. (일) 13:05:49 KST
scarf@TG02:~/repo/chrono$ cargo test --package chrono --test dateutils --features unstable-locales -- try_verify_against_date_command_format --exact --nocapture 
   Compiling chrono v0.4.24 (/home/scarf/repo/chrono)
    Finished test [unoptimized + debuginfo] target(s) in 1.01s
     Running tests/dateutils.rs (target/debug/deps/dateutils-917f84c226dfcdb1)

running 1 test
thread 'try_verify_against_date_command_format' panicked at 'assertion failed: `(left == right)`
  left: `"d01 D01/01/70 F1970-01-01 H12 I12 j001 k12 l12 m01 M11 S13 T12:11:13 u4 U00 w4 W00 X12시 11분 13초 y70 Y1970 z+09:00\n"`,
 right: `"d01 D01/01/70 F1970-01-01 H12 I12 j001 k12 l12 m01 M11 S13 T12:11:13 u4 U00 w4 W00 X12:11:13 y70 Y1970 z+09:00\n"`', tests/dateutils.rs:121:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test try_verify_against_date_command_format ... FAILED

failures:

failures:
    try_verify_against_date_command_format

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s

error: test failed, to rerun pass `-p chrono --test dateutils`
scarf@TG02:~/repo/chrono$ 
```

</details> 


<details><summary>with `LANG=c`</summary>

scarf@TG02:~/repo/chrono$ export LANG=c
scarf@TG02:~/repo/chrono$ date
Sun May 28 13:06:42 KST 2023
scarf@TG02:~/repo/chrono$ cargo test --package chrono --test dateutils --features unstable-locales -- try_verify_against_date_command_format --exact --nocapture 
    Finished test [unoptimized + debuginfo] target(s) in 0.03s
     Running tests/dateutils.rs (target/debug/deps/dateutils-917f84c226dfcdb1)

running 1 test
test try_verify_against_date_command_format ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.14s

scarf@TG02:~/repo/chrono$ 


</details> 

while it could be solved by setting its [env](https://doc.rust-lang.org/std/process/struct.Command.html#method.env) explicitly, but would it suffice to set its env explicitly to `c`?

**Comment by jtmoon79** [comment]
> while it could be solved by setting its [env](https://doc.rust-lang.org/std/process/struct.Command.html#method.env) explicitly, but would it suffice to set its env explicitly to c?

This is a good fix.

<br/>

---

Here is an off-hand idea for anyone to pick-up (not required for this Issue):
It would be good to also run the `try_verify_against_date_command_format` test with `LANG` intentionally set to other values, such as `ko_KR.UTF-8`.
- For the github Actions tests, the locales would need to be installed and somehow a setting signals to the test case that these other `LANG` tests should be run.
- For developers, these additional tests could simply be skipped. Or maybe some other check is done for what locales are available and so can be tested.

**Comment by jtmoon79** [comment]
Interesting, fails for me too using `LANG=en_US.UTF-8`. Using 656c941fc4293d1832ae273b26e78c2ae1f3a505

```text
$ echo $LANG
en_US.UTF-8

$ /usr/bin/date --version
date (GNU coreutils) 8.32
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David MacKenzie.

$ /usr/bin/date
Sat May 27 09:42:48 PM PDT 2023

$ cargo test try_verify_against_date_command_format -- --nocapture
    Finished test [unoptimized + debuginfo] target(s) in 0.07s
     Running unittests src/lib.rs (target/debug/deps/chrono-ab709be662cf80de)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 181 filtered out; finished in 0.00s

     Running tests/dateutils.rs (target/debug/deps/dateutils-94200521e6ba6b56)

running 1 test
thread 'try_verify_against_date_command_format' panicked at 'assertion failed: `(left == right)`
  left: `"d01 D01/01/70 F1970-01-01 H12 I12 j001 k12 l12 m01 M11 S13 T12:11:13 u4 U00 w4 W00 X12:11:13 PM y70 Y1970 z-08:00\n"`,
 right: `"d01 D01/01/70 F1970-01-01 H12 I12 j001 k12 l12 m01 M11 S13 T12:11:13 u4 U00 w4 W00 X12:11:13 y70 Y1970 z-08:00\n"`', tests/dateutils.rs:138:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test try_verify_against_date_command_format ... FAILED

failures:

failures:
    try_verify_against_date_command_format

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s

error: test failed, to rerun pass `--test dateutils`
```

**Comment by pitdicker** [comment]
Fixed in https://github.com/chronotope/chrono/pull/1089.
