### ISSUE TITLE
Bug report: error in `bench_datetime_to_rfc2822`

### ISSUE THREAD

**Issue by yunji-yunji** [chronotope/chrono#1622]
There appears to be an error in `to_rfc2822` function. This error is found by `bench_datetime_to_rfc2822` bench function in `bench/benches/chrono.rs`.

### Reproducible code with error causing inputs
```
#[test]
pub fn test_datetime_to_string() {

    // Error causing inputs: `year` is causing error
    let (year, month, day, hour, min, sec, nanosec, pst_sec) 
        = (-2979, 7, 6, 9, 57, 9, 679244465, -30851);

    let pst = FixedOffset::east_opt(pst_sec).unwrap();
    let dt = pst
        .from_local_datetime(
            &NaiveDate::from_ymd_opt(year, month, day)
                .unwrap()
                .and_hms_nano_opt(hour, min, sec, nanosec)
                .unwrap(),
        )
        .unwrap();

    // Error caused by this line
    let res2822 = dt.to_rfc2822();
    let res3339 = dt.to_rfc3339();
    let res3339_opts = dt.to_rfc3339_opts(SecondsFormat::Nanos, true);

    println!("res 2822 {}, res 3339 {}, res opt {}", res2822, res3339, res3339_opts);
}
```

### Error message and backtrace
```
running 1 test
test bench_chrono::test_datetime_to_string ... FAILED

successes:

successes:

failures:

---- bench_chrono::test_datetime_to_string stdout ----
thread 'bench_chrono::test_datetime_to_string' panicked at src/datetime/mod.rs:626:14:
writing rfc2822 datetime to string should never fail: Error
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5069856495870486134dd2ca0b0e2516308c5c2a/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/5069856495870486134dd2ca0b0e2516308c5c2a/library/core/src/panicking.rs:74:14
   2: core::result::unwrap_failed
             at /rustc/5069856495870486134dd2ca0b0e2516308c5c2a/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::expect
             at /rustc/5069856495870486134dd2ca0b0e2516308c5c2a/library/core/src/result.rs:1059:23
   4: chrono::datetime::DateTime<Tz>::to_rfc2822
             at ./src/datetime/mod.rs:625:9
   5: chrono::bench_chrono::test_datetime_to_string
             at ./src/bench_chrono.rs:263:19
   6: chrono::bench_chrono::test_datetime_to_string::{{closure}}
             at ./src/bench_chrono.rs:247:33
   7: core::ops::function::FnOnce::call_once
             at /rustc/5069856495870486134dd2ca0b0e2516308c5c2a/library/core/src/ops/function.rs:250:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/5069856495870486134dd2ca0b0e2516308c5c2a/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    bench_chrono::test_datetime_to_string

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 255 filtered out; finished in 0.07s
```

**Comment by djc** [comment]
`to_rfc2822()` docs:

```
    /// Returns an RFC 2822 date and time string such as `Tue, 1 Jul 2003 10:52:37 +0200`.
    ///
    /// # Panics
    ///
    /// Panics if the date can not be represented in this format: the year may not be negative and
    /// can not have more than 4 digits.
```

**Comment by yunji-yunji** [comment]
Thank you for your reply. I thought this is an error since my inputs satisfies the conditions in  `from_ymd_opt` docs (I attached below) and it seems like the input  `DateTime` of `to_rfc2822` is formatted okay like `Single(-2979-07-06T09:57:09.679244465-08:34:11)`. Is there some reason why formatting with rfc2822 is not possible in this case?

###  `from_ymd_opt` docs:
```
    /// # Errors
    ///
    /// Returns `None` if:
    /// - The specified calendar day does not exist (for example 2023-04-31).
    /// - The value for `month` or `day` is invalid.
    /// - `year` is out of range for `NaiveDate`.
```

**Comment by djc** [comment]
Yes, because RFC 2822 disallows it:

```
year            =       4*DIGIT / obs-year
obs-year        =       [CFWS] 2*DIGIT [CFWS]
```

**Comment by yunji-yunji** [comment]
I got it. Thanks for the explanation.
