### ISSUE TITLE
serde_json parser format json data "2020-12-12 23:23:23" fail

### ISSUE THREAD

**Issue by zhuxiujia** [chronotope/chrono#466]
```rust
called `Result::unwrap()` on an `Err` value: Decode("[rbatis] json decode: alloc::vec::Vec<example::BizActivity>, fail:premature end of input")
thread 'test_prepare_sql' panicked at 'called `Result::unwrap()` on an `Err` value: Decode("[rbatis] json decode: alloc::vec::Vec<example::BizActivity>, fail:premature end of input")', examplesrcmain.rs:119:39
stack backtrace:
   0: backtrace::backtrace::dbghelp::trace
             at C:UsersVssAdministrator.cargo
egistrysrcgithub.com-1ecc6299db9ec82acktrace-0.3.46sracktrace/dbghelp.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at C:UsersVssAdministrator.cargo
egistrysrcgithub.com-1ecc6299db9ec82acktrace-0.3.46sracktrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at srclibstdsys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at srclibstdsys_common/backtrace.rs:59
   4: core::fmt::write
             at srclibcoremt/mod.rs:1076
   5: std::io::Write::write_fmt
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54srclibstdio/mod.rs:1537
   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
             at srclibstdio/impls.rs:176
   7: std::sys_common::backtrace::_print
             at srclibstdsys_common/backtrace.rs:62
   8: std::sys_common::backtrace::print
             at srclibstdsys_common/backtrace.rs:49
   9: std::panicking::default_hook::{{closure}}
             at srclibstd/panicking.rs:198
  10: std::panicking::default_hook
             at srclibstd/panicking.rs:215
  11: std::panicking::rust_panic_with_hook
             at srclibstd/panicking.rs:486
  12: rust_begin_unwind
             at srclibstd/panicking.rs:388
  13: core::panicking::panic_fmt
             at srclibcore/panicking.rs:101
  14: core::option::expect_none_failed
             at srclibcore/option.rs:1272
  15: core::result::Result<T,E>::unwrap
             at C:Usersmayn.rustup	oolchainsstable-x86_64-pc-windows-gnulib/rustlib/src/rustsrclibcore/result.rs:1005
  16: example::test_prepare_sql::{{closure}}
             at examplesrc/main.rs:119
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at C:Usersmayn.rustup	oolchainsstable-x86_64-pc-windows-gnulib/rustlib/src/rustsrclibcoreuture/mod.rs:73
  18: <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll::{{closure}}
             at C:Usersmayn.cargo
egistrysrcgithub.com-1ecc6299db9ec823async-std-1.6.2src	ask/builder.rs:198
  19: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}
             at C:Usersmayn.cargo
egistrysrcgithub.com-1ecc6299db9ec823async-std-1.6.2src	ask/task_locals_wrapper.rs:60
  20: std::thread::local::LocalKey<T>::try_with
             at C:Usersmayn.rustup	oolchainsstable-x86_64-pc-windows-gnulib/rustlib/src/rustsrclibstd	hread/local.rs:263
  21: std::thread::local::LocalKey<T>::with
             at C:Usersmayn.rustup	oolchainsstable-x86_64-pc-windows-gnulib/rustlib/src/rustsrclibstd	hread/local.rs:239
  22: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current
             at C:Usersmayn.cargo
egistrysrcgithub.com-1ecc6299db9ec823async-std-1.6.2src	ask/task_locals_wrapper.rs:55
  23: <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll
             at C:Usersmayn.cargo
egistrysrcgithub.com-1ecc6299db9ec823async-std-1.6.2src	ask/builder.rs:196
  24: smol::run::run::{{closure}}::{{closure}}
             at C:Usersmayn.cargo
egistrysrcgithub.com-1ecc6299db9ec823smol-0.1.18src/run.rs:119
  25: scoped_tls::ScopedKey<T>::set
             at C:Usersmayn.cargo
egistrysrcgithub.com-1ecc6299db9ec823scoped-tls-1.0.0src/lib.rs:137
  26: smol::run::run::{{closure}}
             at C:Usersmayn.cargo
egistrysrcgithub.com-1ecc6299db9ec823smol-0.1.18src/run.rs:116
  27: smol::context::enter
             at C:Usersmayn.cargo
egistrysrcgithub.com-1ecc6299db9ec823smol-0.1.18src/context.rs:8
  28: smol::run::run
             at C:Usersmayn.cargo
egistrysrcgithub.com-1ecc6299db9ec823smol-0.1.18src/run.rs:115
  29: async_std::task::builder::Builder::blocking::{{closure}}::{{closure}}
             at C:Usersmayn.cargo
egistrysrcgithub.com-1ecc6299db9ec823async-std-1.6.2src	ask/builder.rs:170
  30: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}
             at C:Usersmayn.cargo
egistrysrcgithub.com-1ecc6299db9ec823async-std-1.6.2src	ask/task_locals_wrapper.rs:60
  31: std::thread::local::LocalKey<T>::try_with
             at C:Usersmayn.rustup	oolchainsstable-x86_64-pc-windows-gnulib/rustlib/src/rustsrclibstd	hread/local.rs:263
  32: std::thread::local::LocalKey<T>::with
             at C:Usersmayn.rustup	oolchainsstable-x86_64-pc-windows-gnulib/rustlib/src/rustsrclibstd	hread/local.rs:239
  33: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current
             at C:Usersmayn.cargo
egistrysrcgithub.com-1ecc6299db9ec823async-std-1.6.2src	ask/task_locals_wrapper.rs:55
  34: async_std::task::builder::Builder::blocking::{{closure}}
             at C:Usersmayn.cargo
egistrysrcgithub.com-1ecc6299db9ec823async-std-1.6.2src	ask/builder.rs:167
  35: std::thread::local::LocalKey<T>::try_with
             at C:Usersmayn.rustup	oolchainsstable-x86_64-pc-windows-gnulib/rustlib/src/rustsrclibstd	hread/local.rs:263
  36: std::thread::local::LocalKey<T>::with
             at C:Usersmayn.rustup	oolchainsstable-x86_64-pc-windows-gnulib/rustlib/src/rustsrclibstd	hread/local.rs:239
  37: async_std::task::builder::Builder::blocking
             at C:Usersmayn.cargo
egistrysrcgithub.com-1ecc6299db9ec823async-std-1.6.2src	ask/builder.rs:160
  38: async_std::task::block_on::block_on
             at C:Usersmayn.cargo
egistrysrcgithub.com-1ecc6299db9ec823async-std-1.6.2src	ask/block_on.rs:33
  39: example::test_prepare_sql
             at examplesrc/main.rs:113
  40: example::test_prepare_sql::{{closure}}
             at examplesrc/main.rs:112
  41: core::ops::function::FnOnce::call_once
             at C:Usersmayn.rustup	oolchainsstable-x86_64-pc-windows-gnulib/rustlib/src/rustsrclibcoreops/function.rs:232
  42: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54srcliballoc/boxed.rs:1076
  43: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54srclibstd/panic.rs:318
```

**Comment by quodlibetor** [comment]
What code is failing?
